import { Tour } from '../models/Tour';
import { logger } from './logger';

export const INITIAL_TOURS = [
  {
    slug: 'rajasthan-royal-escape',
    title: 'The Royal Escape',
    destination: 'Rajasthan, India',
    category: 'Heritage & Temples',
    duration: '6 Days / 5 Nights',
    durationDays: 6,
    groupSize: 'Private / Couple / Family',
    rating: 4.98,
    reviewsCount: 384,
    price: 24999,
    originalPrice: 28999,
    discountPercent: 14,
    heroImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1600&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1200&q=80',
    ],
    overview:
      'Experience the royal charm of Rajasthan with a journey through majestic forts, golden deserts and vibrant culture. From the grand palaces of Jaipur to the serene lakes of Udaipur, this trip is a perfect blend of history, luxury and adventure.',
    tags: ['Heritage', 'Culture', 'Luxury'],
    tripType: 'Private Tour',
    bestTime: 'Oct - Mar',
    startEnd: 'Jaipur - Udaipur',
    inclusions: [
      '5 Nights in curated Heritage Palaces & Luxury Boutique Stays',
      'Daily Royal Breakfast and Traditional Rajasthani Thali Dinners',
      'Private Chauffeur-driven AC Sedan / SUV for full circuit',
      'Sunset Boat Cruise on Lake Pichola, Udaipur',
      'Monument entry passes and licensed English-speaking historians',
      'All toll taxes, parking fees, fuel, and chauffeur allowances',
    ],
    exclusions: [
      'Flights or train tickets to Jaipur / from Udaipur',
      'Personal expenses, shopping, laundry, and tips',
      'Camera entry fees at select monuments',
      'Travel insurance (available upon request)',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Jaipur • City Tour',
        description:
          'Arrive at Jaipur Airport/Station and receive a traditional royal welcome. Transfer to your heritage hotel. In the afternoon, visit the iconic Hawa Mahal facade and explore the historic colorful lanes of Johari Bazaar.',
        meals: 'Royal Welcome Dinner',
        accommodation: 'Shahpura Haveli / Trident Jaipur',
      },
      {
        day: 2,
        title: 'Jaipur • Amber Fort & Local Markets',
        description:
          'Morning ascent to Amber Fort perched on the rugged Aravalli hills with its stunning Sheesh Mahal mirror palace. Afternoon visits to the City Palace museum and Jantar Mantar astronomical observatory. Evening sunset view at Nahargarh Fort.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Shahpura Haveli / Trident Jaipur',
      },
      {
        day: 3,
        title: 'Jodhpur • Mehrangarh Fort',
        description:
          'Scenic journey through the desert landscape toward the Sun City of Jodhpur. Check into your heritage haveli and tour the imposing Mehrangarh Fort, Jaswant Thada marble cenotaph, and the lively blue alleys of Brahmpuri.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Ajit Bhawan Palace Jodhpur',
      },
      {
        day: 4,
        title: 'Udaipur • City Palace & Lake',
        description:
          'Scenic drive via the intricate 15th-century marble temple of Ranakpur to Udaipur, the Venice of the East. Check in to your lakeside property and enjoy an exclusive sunset motorboat cruise on Lake Pichola with views of Jag Mandir.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Fateh Garh Heritage Resort Udaipur',
      },
      {
        day: 5,
        title: 'Udaipur • Leisure Day',
        description:
          'Morning guided tour of the majestic Udaipur City Palace complex, followed by the tranquil fountains of Saheliyon Ki Bari and Bagore Ki Haveli. Evening at leisure overlooking shimmering waters and rooftop dining.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Fateh Garh Heritage Resort Udaipur',
      },
      {
        day: 6,
        title: 'Departure from Udaipur',
        description:
          'Savor a relaxed breakfast overlooking the lake. Enjoy some free time for artisan shopping in the old town before a private chauffeur transfer to Udaipur Airport for your onward journey.',
        meals: 'Breakfast',
      },
    ],
    featured: true,
    bestSeller: true,
    isPublished: true,
  },
  {
    slug: 'kerala-backwaters',
    title: 'Kerala Backwaters',
    destination: 'Kerala, India',
    category: 'Coastal & Backwaters',
    duration: '4 Days / 3 Nights',
    durationDays: 4,
    groupSize: 'Private / Couple / Family',
    rating: 4.95,
    reviewsCount: 420,
    price: 16999,
    originalPrice: 20999,
    discountPercent: 19,
    heroImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1600&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    ],
    overview:
      'Glide through the tranquil palm-fringed backwaters of Alleppey and Kumarakom aboard an authentic private houseboat. Savor traditional Kerala cuisine and unwind with rejuvenating Ayurvedic wellness experiences.',
    tags: ['Houseboat', 'Wellness', 'Nature'],
    tripType: 'Private Tour',
    bestTime: 'Sep - Mar',
    startEnd: 'Cochin - Alleppey - Cochin',
    inclusions: [
      '1 Night Deluxe Private Houseboat with All Meals',
      '2 Nights Luxury Lakeside Resort in Kumarakom',
      'Daily Authentic Kerala Breakfast & Dinners',
      'Private AC Cab for all airport transfers and sightseeing',
      'Complimentary 60-min Ayurvedic rejuvenation massage',
    ],
    exclusions: ['Airfare to Cochin', 'Personal expenses & tips'],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Cochin & Transfer to Alleppey Houseboat',
        description: 'Meet chauffeur at Cochin Airport. Board your private houseboat by noon. Cruise through canals with lunch and sunset tea.',
        meals: 'Lunch & Dinner',
        accommodation: 'Alleppey Premium Houseboat',
      },
      {
        day: 2,
        title: 'Kumarakom Lakeside Resort Check-in & Bird Sanctuary',
        description: 'Morning tea on the water, disembark and transfer to Kumarakom. Visit bird sanctuary and enjoy Ayurvedic spa therapy.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Coconut Lagoon Kumarakom',
      },
      {
        day: 3,
        title: 'Village Canoe Cruise & Sunset Over Lake Vembanad',
        description: 'Guided quiet shikara canoe ride through narrow canals, watching coir weavers and toddy tappers. Sunset cocktail cruise.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Coconut Lagoon Kumarakom',
      },
      {
        day: 4,
        title: 'Fort Kochi Heritage Stroll & Departure',
        description: 'Drive to Fort Kochi to see Chinese fishing nets and Jewish Synagogue before transfer to Cochin International Airport.',
        meals: 'Breakfast',
      },
    ],
    featured: true,
    bestSeller: true,
    isPublished: true,
  },
  {
    slug: 'ladakh-adventure',
    title: 'Ladakh Adventure',
    destination: 'Ladakh, India',
    category: 'Adventure',
    duration: '7 Days / 6 Nights',
    durationDays: 7,
    groupSize: 'Private / Adventure Group',
    rating: 4.96,
    reviewsCount: 310,
    price: 28499,
    originalPrice: 34999,
    discountPercent: 18,
    heroImage: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1600&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80',
    ],
    overview:
      'Traverse the highest motorable passes in the world, explore ancient monasteries perched on craggy peaks, and camp beneath starlit skies by the brilliant blue waters of Pangong Tso lake.',
    tags: ['Mountains', 'Thrill', 'Peace'],
    tripType: 'Private Tour',
    bestTime: 'May - Sep',
    startEnd: 'Leh - Leh',
    inclusions: [
      '6 Nights in Luxury Boutique Hotels & Deluxe Glamping Tents',
      'Daily Buffet Breakfast and Ladakhi Dinners',
      'Private 4x4 SUV (Innova / Fortuner) with experienced mountain driver',
      'Inner Line Permits for Nubra Valley & Pangong Lake',
      'Oxygen cylinder on board for high altitude comfort',
    ],
    exclusions: ['Flights to Leh', 'Camel ride in Hunder dunes', 'Personal expenses'],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Leh & Acclimatization',
        description: 'Land at Leh Airport (11,500 ft). Transfer to hotel and complete day of rest to acclimatize. Gentle evening walk to Shanti Stupa.',
        meals: 'Dinner',
        accommodation: 'The Grand Dragon Leh',
      },
      {
        day: 2,
        title: 'Sham Valley: Magnetic Hill & Sangam Confluence',
        description: 'Drive along the Indus and Zanskar confluence, test the optical illusion at Magnetic Hill, and visit Gurudwara Pathar Sahib.',
        meals: 'Breakfast & Dinner',
        accommodation: 'The Grand Dragon Leh',
      },
      {
        day: 3,
        title: 'Leh to Nubra Valley via Khardung La Pass (17,982 ft)',
        description: 'Cross the world-famous Khardung La pass. Descend into Nubra Valley and ride double-humped Bactrian camels in Hunder sand dunes.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Stone Hedge Luxury Camp Nubra',
      },
      {
        day: 4,
        title: 'Diskit Monastery & Drive to Pangong Tso Lake',
        description: 'Visit the colossal Maitreya Buddha statue in Diskit. Drive along the scenic Shyok river to the turquoise waters of Pangong Tso.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Pangong Glamping Retreat',
      },
      {
        day: 5,
        title: 'Sunrise at Pangong & Return to Leh via Chang La',
        description: 'Wake up to surreal sunrise reflecting over the high alpine lake. Cross Chang La pass (17,688 ft) and visit Thiksey Monastery.',
        meals: 'Breakfast & Dinner',
        accommodation: 'The Grand Dragon Leh',
      },
      {
        day: 6,
        title: 'Hemis Monastery & Local Crafts Market',
        description: 'Discover the largest monastery in Ladakh at Hemis. Afternoon shopping for authentic Pashmina, silver, and apricots in Leh market.',
        meals: 'Breakfast & Dinner',
        accommodation: 'The Grand Dragon Leh',
      },
      {
        day: 7,
        title: 'Departure from Leh',
        description: 'Early morning transfer to Leh Airport with unforgettable memories of the Himalayas.',
        meals: 'Breakfast',
      },
    ],
    featured: true,
    bestSeller: true,
    isPublished: true,
  },
  {
    slug: 'meghalaya-escape',
    title: 'Meghalaya Escape',
    destination: 'Meghalaya, India',
    category: 'Hill Station',
    duration: '5 Days / 4 Nights',
    durationDays: 5,
    groupSize: 'Private / Couple / Small Group',
    rating: 4.93,
    reviewsCount: 228,
    price: 22499,
    originalPrice: 26999,
    discountPercent: 16,
    heroImage: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1600&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1200&q=80',
    ],
    overview:
      'Immerse yourself in the Abode of Clouds. Trek across centuries-old Double Decker Living Root Bridges, swim in the crystalline emerald waters of Dawki, and explore cascading Cherrapunji waterfalls.',
    tags: ['Clouds', 'Adventure', 'Valleys'],
    tripType: 'Private Tour',
    bestTime: 'Oct - May',
    startEnd: 'Guwahati - Shillong - Guwahati',
    inclusions: [
      '4 Nights in Luxury Forest Eco-Resorts & Heritage Stays',
      'Daily Farm-fresh Breakfast and Khasi Traditional Dinners',
      'Private AC Cab for Guwahati pickup, sightseeing, and drop',
      'Boating at Umngot River, Dawki (crystal-clear water)',
      'Local Khasi tribal trekking guide for Root Bridges',
    ],
    exclusions: ['Airfare to Guwahati', 'Cave exploration gears', 'Personal expenses'],
    itinerary: [
      {
        day: 1,
        title: 'Guwahati to Shillong via Umiam Lake',
        description: 'Chauffeur pickup at Guwahati. Scenic uphill drive to Shillong, stopping by the vast waters of Umiam Lake for water sports.',
        meals: 'Dinner',
        accommodation: 'Ri Kynjai Resort Shillong',
      },
      {
        day: 2,
        title: 'Shillong to Cherrapunji: Nohkalikai Falls & Caves',
        description: 'Drive along misty ravines to Sohra (Cherrapunji). Gaze at India’s tallest plunge waterfall Nohkalikai and explore Mawsmai Cave.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Polo Orchid Resort Cherrapunji',
      },
      {
        day: 3,
        title: 'Nongriat Double Decker Living Root Bridge Trek',
        description: 'Hike through lush rainforest steps to witness the bio-engineering marvel of bio-living root bridges and turquoise natural pools.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Polo Orchid Resort Cherrapunji',
      },
      {
        day: 4,
        title: 'Mawlynnong Cleanest Village & Dawki Glass River',
        description: 'Visit Asia’s cleanest village Mawlynnong and take a boat ride on the crystal transparent waters of Dawki river bordering Bangladesh.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Ri Kynjai Resort Shillong',
      },
      {
        day: 5,
        title: 'Don Bosco Museum & Guwahati Departure',
        description: 'Morning exploration of indigenous tribal heritage at Don Bosco Museum, followed by drop-off at Guwahati Airport.',
        meals: 'Breakfast',
      },
    ],
    featured: true,
    bestSeller: false,
    isPublished: true,
  },
  {
    slug: 'goa-beach-holiday',
    title: 'Goa Beach Holiday',
    destination: 'Goa, India',
    category: 'Coastal & Backwaters',
    duration: '4 Days / 3 Nights',
    durationDays: 4,
    groupSize: 'Private / Couple / Friends',
    rating: 4.89,
    reviewsCount: 395,
    price: 14999,
    originalPrice: 18999,
    discountPercent: 21,
    heroImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1600&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80',
    ],
    overview:
      'Unwind on sun-kissed beaches, Portuguese colonial villas, and serene coastal sunsets. From beach shacks in South Goa to historic churches in Old Goa, enjoy the ultimate relaxed tropical getaway.',
    tags: ['Beaches', 'Relaxation', 'Nightlife'],
    tripType: 'Private Tour',
    bestTime: 'Oct - Apr',
    startEnd: 'Goa - Goa',
    inclusions: [
      '3 Nights in 4-Star Beachfront Resort with Swimming Pool',
      'Daily Buffet Breakfast and Welcome Coastal Drinks',
      'Private AC Cab for North & South Goa Sightseeing',
      'Sunset Mandovi River Cruise with Goan folk music',
      'All airport/station pickup and drop-off transfers',
    ],
    exclusions: ['Airfare / Train tickets', 'Watersports activities', 'Personal shopping'],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Goa & Sunset Beach Walk',
        description: 'Chauffeur pickup from Goa Airport / Mopa. Transfer to your beach resort. Relax by the pool and evening sunset stroll on Candolim Beach.',
        meals: 'Welcome Drink & Dinner',
        accommodation: 'Taj Fort Aguada Resort & Spa',
      },
      {
        day: 2,
        title: 'South Goa Heritage: Old Goa Churches & Spice Farm',
        description: 'Visit the UNESCO Basilica of Bom Jesus, Se Cathedral, followed by an aromatic Goan spice plantation tour with buffet lunch.',
        meals: 'Breakfast & Traditional Lunch',
        accommodation: 'Taj Fort Aguada Resort & Spa',
      },
      {
        day: 3,
        title: 'North Goa: Fort Aguada, Chapora & Sunset Cruise',
        description: 'Tour the 17th-century Portuguese Fort Aguada, Chapora Fort overlooking Vagator, and an evening dinner cruise on the Mandovi.',
        meals: 'Breakfast & Dinner',
        accommodation: 'Taj Fort Aguada Resort & Spa',
      },
      {
        day: 4,
        title: 'Leisurely Beach Morning & Departure',
        description: 'Enjoy a relaxed breakfast and morning swim in the sea before private transfer to the airport.',
        meals: 'Breakfast',
      },
    ],
    featured: true,
    bestSeller: false,
    isPublished: true,
  },
  {
    slug: 'himalayan-trails',
    title: 'Himalayan Trails',
    destination: 'Himachal Pradesh, India',
    category: 'Adventure',
    duration: '6 Days / 5 Nights',
    durationDays: 6,
    groupSize: 'Private / Couple / Adventure',
    rating: 4.94,
    reviewsCount: 340,
    price: 27999,
    originalPrice: 32999,
    discountPercent: 15,
    heroImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1200&q=80',
    ],
    overview:
      'Trek through soaring cedar pine forests, apple orchards of Manali, and the breathtaking alpine valleys of Solang and Sethan. Designed for mountain lovers and outdoor enthusiasts seeking pristine Himalayan air.',
    tags: ['Trekking', 'Alpine', 'Scenic'],
    tripType: 'Private Tour',
    bestTime: 'Mar - Jun & Sep - Nov',
    startEnd: 'Chandigarh - Manali - Chandigarh',
    inclusions: [
      '5 Nights Deluxe Cedar Wood Mountain Chalets',
      'Daily Hearty Himalayan Breakfast and Dinners',
      'Private AC SUV with high-altitude experienced driver',
      'Guided alpine day hike to Jogini Waterfalls & Solang Valley',
      'Evening bonfire with live acoustic music',
    ],
    exclusions: ['Paragliding / zipline tickets', 'Warm wear gear rentals', 'Personal shopping'],
    itinerary: [
      {
        day: 1,
        title: 'Chandigarh to Manali Scenic Drive via Beas River',
        description: 'Pickup from Chandigarh. Travel along the roaring Beas river through Mandi and Kullu to reach picturesque Manali.',
        meals: 'Dinner',
        accommodation: 'The Himalayan Manali',
      },
      {
        day: 2,
        title: 'Old Manali, Hadimba Temple & Vashisht Hot Springs',
        description: 'Explore the historic wooden Hadimba Devi Temple, rustic cafes in Old Manali, and the ancient natural sulfur hot springs of Vashisht.',
        meals: 'Breakfast & Dinner',
        accommodation: 'The Himalayan Manali',
      },
      {
        day: 3,
        title: 'Solang Valley & Atal Tunnel to Sissu, Lahaul',
        description: 'Drive through the engineering marvel of Atal Tunnel to witness the raw snow-clad landscape and waterfalls of Sissu in Lahaul Valley.',
        meals: 'Breakfast & Dinner',
        accommodation: 'The Himalayan Manali',
      },
      {
        day: 4,
        title: 'Jogini Waterfalls Forest Trek & Apple Orchards',
        description: 'Guided gentle hike through pinewood paths to the multi-tiered cascades of Jogini waterfall. Visit authentic Himalayan village homes.',
        meals: 'Breakfast & Dinner',
        accommodation: 'The Himalayan Manali',
      },
      {
        day: 5,
        title: 'Naggar Castle & Roerich Art Gallery',
        description: 'Visit the medieval wooden Naggar Castle with sweeping valley vistas and the Russian artist Nicholas Roerich gallery.',
        meals: 'Breakfast & Dinner',
        accommodation: 'The Himalayan Manali',
      },
      {
        day: 6,
        title: 'Kullu Shawl Weavers & Chandigarh Return',
        description: 'Morning drive down through Kullu valley with a stop at traditional handloom weavers before departure drop at Chandigarh.',
        meals: 'Breakfast',
      },
    ],
    featured: true,
    bestSeller: false,
    isPublished: true,
  },
];

export const seedTours = async (force: boolean = false): Promise<number> => {
  try {
    const existingCount = await Tour.countDocuments();
    if (existingCount > 0 && !force) {
      logger.info(`[Tour Seed] Database already contains ${existingCount} tours. Skipping initial seed.`);
      return existingCount;
    }

    if (force && existingCount > 0) {
      await Tour.deleteMany({});
      logger.info('[Tour Seed] Cleared existing tours for forced re-seed.');
    }

    await Tour.insertMany(INITIAL_TOURS);
    logger.info(`[Tour Seed] Successfully seeded ${INITIAL_TOURS.length} default tour packages into MongoDB.`);
    return INITIAL_TOURS.length;
  } catch (error) {
    logger.error(`[Tour Seed Error] Failed to seed tours: ${(error as Error).message}`);
    return 0;
  }
};
